production:
  clients:
    default:
     # The standard MongoDB connection URI allows for easy
     # replica set connection setup.
     # Use environment variables or a config file to keep your
     # credentials safe e.g. <%= ENV['MONGODB_URI'] %>.
     uri: <%= ENV['MONGODB_URI'] %>

     options:
       # The default timeout is 5, which is the time in seconds
       # for a connection to time out.
       # We recommend 15 because it allows for plenty of time
       # in most operating environments.
       connect_timeout: 15

development:
  clients:
    default:
     uri: <%= ENV['MONGODB_URI'] %>
     options:
       connect_timeout: 15
       auth_source: admin

test:
  clients:
    default:
     uri: <%= ENV['MONGODB_TEST_URI'] %>
     options:
       connect_timeout: 15
       auth_source: admin
